"""Generates a single, self-contained, offline HTML report from a scan
result. No CDN dependencies — everything (styling, sorting, filtering) is
inline, so the file works even with no internet connection when opened."""

import html
import json

_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>{app_name} report — {target}</title>
<style>
  :root {{ color-scheme: light dark; }}
  body {{ font-family: -apple-system, Segoe UI, Roboto, sans-serif; margin: 2rem; max-width: 1100px; margin-inline: auto; }}
  h1 {{ margin-bottom: 0.2rem; }}
  .meta {{ color: #666; margin-bottom: 1.5rem; }}
  .stats {{ display: flex; gap: 1rem; margin-bottom: 1.5rem; flex-wrap: wrap; }}
  .stat {{ border: 1px solid #ddd; border-radius: 8px; padding: 0.75rem 1rem; min-width: 120px; }}
  .stat .n {{ font-size: 1.6rem; font-weight: 700; }}
  .stat .l {{ font-size: 0.8rem; color: #777; text-transform: uppercase; }}
  input[type=text] {{ padding: 0.5rem; width: 100%; max-width: 320px; margin-bottom: 1rem; box-sizing: border-box; }}
  table {{ border-collapse: collapse; width: 100%; font-size: 0.9rem; }}
  th, td {{ text-align: left; padding: 0.5rem 0.7rem; border-bottom: 1px solid #eee; vertical-align: top; }}
  th {{ cursor: pointer; user-select: none; position: sticky; top: 0; background: Canvas; }}
  th:hover {{ color: #2563eb; }}
  tr:hover {{ background: rgba(37,99,235,0.06); }}
  .badge {{ display: inline-block; padding: 0.1rem 0.5rem; border-radius: 999px; font-size: 0.75rem; }}
  .badge.new {{ background: #dcfce7; color: #166534; }}
  .badge.risk {{ background: #fee2e2; color: #991b1b; }}
  .badge.dead {{ background: #f1f5f9; color: #64748b; }}
  .badge.status2 {{ background: #dcfce7; color: #166534; }}
  .badge.status3 {{ background: #fef9c3; color: #854d0e; }}
  .badge.status4, .badge.status5 {{ background: #fee2e2; color: #991b1b; }}
  code {{ font-size: 0.85em; }}
  footer {{ margin-top: 2rem; color: #999; font-size: 0.8rem; }}
  h2 {{ margin-top: 2rem; font-size: 1.1rem; border-top: 1px solid #eee; padding-top: 1.5rem; }}
  table.kv {{ width: auto; min-width: 320px; }}
  table.kv th {{ position: static; background: none; cursor: default; width: 110px; }}
  .unavailable {{ color: #888; font-style: italic; }}
  ul.external-list {{ margin: 0.5rem 0; padding-left: 1.2rem; }}
  ul.external-list li {{ margin-bottom: 0.25rem; }}
</style>
</head>
<body>
  <h1>{app_name} report</h1>
  <div class="meta">Target: <code>{target}</code> &middot; Generated by {app_name} v{version}</div>

  <div class="stats">
    <div class="stat"><div class="n">{subdomain_count}</div><div class="l">Subdomains found</div></div>
    <div class="stat"><div class="n">{resolving_count}</div><div class="l">Currently resolving</div></div>
    <div class="stat"><div class="n">{live_count}</div><div class="l">Responding to HTTP</div></div>
    <div class="stat"><div class="n">{new_count}</div><div class="l">New since last scan</div></div>
    <div class="stat"><div class="n">{risk_count}</div><div class="l">Possible takeover risk</div></div>
  </div>

  <input type="text" id="filterBox" placeholder="Filter by hostname or IP...">

  <table id="report">
    <thead>
      <tr>
        <th data-key="host">Host</th>
        <th data-key="ips">IP(s)</th>
        <th data-key="status_code">Status</th>
        <th data-key="title">Title</th>
        <th data-key="risk">Risk</th>
        <th data-key="new">Flag</th>
      </tr>
    </thead>
    <tbody>
      {rows}
    </tbody>
  </table>
{email_section}{dns_section}{external_section}
  <footer>Generated locally &middot; no data leaves your machine from this file.</footer>

<script>
const filterBox = document.getElementById('filterBox');
const tbody = document.querySelector('#report tbody');
const rows = Array.from(tbody.querySelectorAll('tr'));

filterBox.addEventListener('input', () => {{
  const q = filterBox.value.toLowerCase();
  rows.forEach(r => {{
    r.style.display = r.dataset.search.includes(q) ? '' : 'none';
  }});
}});

let sortDir = {{}};
document.querySelectorAll('th[data-key]').forEach(th => {{
  th.addEventListener('click', () => {{
    const key = th.dataset.key;
    sortDir[key] = !sortDir[key];
    const sorted = rows.slice().sort((a, b) => {{
      const av = a.dataset[key] || '';
      const bv = b.dataset[key] || '';
      return sortDir[key] ? av.localeCompare(bv, undefined, {{numeric: true}}) : bv.localeCompare(av, undefined, {{numeric: true}});
    }});
    sorted.forEach(r => tbody.appendChild(r));
  }});
}});
</script>
</body>
</html>
"""

_ROW_TEMPLATE = """<tr data-search="{search}" data-host="{host}" data-ips="{ips_sort}" data-status_code="{status_sort}" data-title="{title_sort}" data-risk="{risk_sort}" data-new="{new_sort}">
  <td><code>{host}</code></td>
  <td>{ips_display}</td>
  <td>{status_badge}</td>
  <td>{title_display}</td>
  <td>{risk_badge}</td>
  <td>{new_badge}</td>
</tr>"""


def _status_badge(status_code):
    if status_code is None:
        return '<span class="badge dead">no response</span>'
    cls = f"status{str(status_code)[0]}"
    return f'<span class="badge {cls}">{status_code}</span>'


def _render_email_section(email_security) -> str:
    """Renders the SPF/DMARC/MX section — only if --email was actually
    used for this scan. Returns an empty string otherwise, so the report
    doesn't show a misleading empty section for data that was never
    requested."""
    if not email_security:
        return ""
    if not email_security.get("available"):
        reason = html.escape(email_security.get("reason", "not available"))
        return f'\n  <h2>Email security</h2>\n  <p class="unavailable">Not checked: {reason}</p>\n'

    spf = email_security.get("spf")
    dmarc = email_security.get("dmarc")
    mx = email_security.get("mx") or []
    spf_display = html.escape(spf) if spf else '<span class="badge dead">not found</span>'
    dmarc_display = html.escape(dmarc) if dmarc else '<span class="badge dead">not found</span>'
    mx_display = html.escape(", ".join(mx)) if mx else "&mdash;"

    return (
        "\n  <h2>Email security</h2>\n"
        '  <table class="kv">\n'
        f"    <tr><th>SPF</th><td>{spf_display}</td></tr>\n"
        f"    <tr><th>DMARC</th><td>{dmarc_display}</td></tr>\n"
        f"    <tr><th>MX records</th><td>{mx_display}</td></tr>\n"
        "  </table>\n"
    )


def _render_dns_section(dns_records) -> str:
    """Renders the NS/MX/TXT section — only if --dns-records was actually
    used for this scan."""
    if not dns_records:
        return ""
    if not dns_records.get("available"):
        return (
            "\n  <h2>DNS records</h2>\n"
            '  <p class="unavailable">Not available (requires dnspython).</p>\n'
        )

    def fmt_list(values):
        return "<br>".join(html.escape(v) for v in values) if values else "&mdash;"

    ns_display = fmt_list(dns_records.get("NS") or [])
    mx_display = fmt_list(dns_records.get("MX") or [])
    txt_display = fmt_list(dns_records.get("TXT") or [])

    return (
        "\n  <h2>DNS records</h2>\n"
        '  <table class="kv">\n'
        f"    <tr><th>NS</th><td>{ns_display}</td></tr>\n"
        f"    <tr><th>MX</th><td>{mx_display}</td></tr>\n"
        f"    <tr><th>TXT</th><td>{txt_display}</td></tr>\n"
        "  </table>\n"
    )


def _render_external_section(external_links) -> str:
    """Renders the list of out-of-scope hosts found while crawling (see
    split_by_scope() in cli.py) — only shown when the list is non-empty,
    since most scans won't have any."""
    if not external_links:
        return ""
    items = "".join(f"    <li><code>{html.escape(h)}</code></li>\n" for h in sorted(external_links))
    return (
        "\n  <h2>External links found (not scanned — different organization)</h2>\n"
        f'  <ul class="external-list">\n{items}  </ul>\n'
    )


def render_html_report(result: dict, version: str = "1.0.0", app_name: str = "ReconCave") -> str:
    """Build the full HTML document as a string from a scan result dict
    (the same structure written to the JSON output). Every optional
    section (email security, DNS records, external links) only renders
    when that data is actually present in the result — a scan that never
    requested --email won't show an empty "Email security" section."""
    subdomains = result.get("subdomains", [])
    new_hosts = set(result.get("diff", {}).get("new", []))

    resolving_count = sum(1 for s in subdomains if s.get("resolves"))
    live_count = sum(1 for s in subdomains if s.get("status_code") is not None)
    risk_count = sum(1 for s in subdomains if (s.get("cname") or {}).get("possible_takeover"))

    rows_html = []
    for s in subdomains:
        host = html.escape(s["host"])
        ips = s.get("ips") or []
        ips_display = ", ".join(html.escape(ip) for ip in ips) if ips else "&mdash;"
        title_display = html.escape(s.get("title") or "")
        is_new = s["host"] in new_hosts
        new_badge = '<span class="badge new">new</span>' if is_new else ""

        is_risk = bool((s.get("cname") or {}).get("possible_takeover"))
        risk_badge = '<span class="badge risk">possible takeover</span>' if is_risk else ""

        rows_html.append(_ROW_TEMPLATE.format(
            search=html.escape(f"{s['host']} {' '.join(ips)}".lower()),
            host=host,
            ips_sort=html.escape(",".join(ips)),
            status_sort=s.get("status_code") if s.get("status_code") is not None else 999,
            title_sort=title_display,
            risk_sort="1" if is_risk else "0",
            new_sort="1" if is_new else "0",
            ips_display=ips_display,
            status_badge=_status_badge(s.get("status_code")),
            title_display=title_display or "&mdash;",
            risk_badge=risk_badge,
            new_badge=new_badge,
        ))

    email_section = _render_email_section(result.get("email_security"))
    dns_section = _render_dns_section(result.get("dns_records"))
    external_section = _render_external_section(result.get("crawl", {}).get("external_links_found"))

    return _TEMPLATE.format(
        app_name=html.escape(app_name),
        target=html.escape(result.get("target", "")),
        version=version,
        subdomain_count=len(subdomains),
        resolving_count=resolving_count,
        live_count=live_count,
        new_count=len(new_hosts),
        risk_count=risk_count,
        rows="\n      ".join(rows_html) if rows_html else "<tr><td colspan=6>No subdomains found.</td></tr>",
        email_section=email_section,
        dns_section=dns_section,
        external_section=external_section,
    )
